#pragma once

void set_tAdd__EmptySet(void);
void set_tAdd__IdenticalElem(void);
void set_tAdd__AnotherElem(void);
void set_tCheck__EmptySet(void);
void set_tCheck__NonEmptySet(void);
void set_tCheck__ExistingElem(void);
void set_tRemove__NonExistingElem(void);
void set_tRemove__ExistingElem(void);
void set_tIntersection__2EmptySets(void);
void set_tIntersection__1EmptySet(void);
void set_tIntersection__WithoutIntersection(void);
void set_tIntersection__WithIntersection(void);
void set_tUnion__2EmptySets(void);
void set_tUnion__1EmptySet(void);
void set_tUnion__WithoutIntersection(void);
void set_tUnion__WithIntersection(void);